export const registerFormFields = {
  email: {
    type: "text" as const,
    label: "Email",
    placeholder: "test@test.com",
    errorMessage: "Invalid Email",
    regex:
      "([!#-'*+/-9=?A-Z^-~-]+(.[!#-'*+/-9=?A-Z^-~-]+)*|\"([]!#-[^-~ \t]|(\\[\t -~]))+\")@([!#-'*+/-9=?A-Z^-~-]+(.[!#-'*+/-9=?A-Z^-~-]+)*|[[\t -Z^-~]*])",
    initialData: "",
    disabled: false,
  },
  password: {
    type: "password" as const,
    label: "Password",
    placeholder: "********",
    errorMessage:
      "Invalid Password. Must contain atleast 1 Uppercase character, 1 Lowercase character, 1 number, 1 symbol and have minimum length of 8",
    regex:
      "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,}$",
    initialData: "",
    disabled: false,
  },
  name: {
    type: "text" as const,
    label: "Name",
    placeholder: "John doe",
    regex: "^.{5,30}$",
    errorMessage: "Name must have 5 to 30 characters",
    initialData: "",
    disabled: false,
  },
  designation: {
    type: "text" as const,
    label: "Designation",
    placeholder: "Manager",
    regex: "^(?!s*$).+",
    errorMessage: "Designation cannot be blank",
    initialData: "",
    disabled: false,
  },
  department: {
    type: "text" as const,
    label: "Department",
    placeholder: "Technology",
    regex: "^(?!s*$).+",
    errorMessage: "Department cannot be blank",
    initialData: "",
    disabled: false,
  },
  gender: {
    type: "select" as const,
    name: "gender",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "other", label: "Other" },
    ],
    label: "Gender",
    placeholder: "Male",
    regex: null,
    errorMessage: null,
    initialData: "",
    disabled: false,
  },
  dob: {
    type: "date" as const,
    label: "Date of Birth",
    placeholder: "dd-mm-yyyy",
    regex: null,
    errorMessage: null,
    initialData: "",
    disabled: false,
  },
  doj: {
    type: "date" as const,
    label: "Date of Joining",
    placeholder: "dd-mm-yyyy",
    regex: null,
    errorMessage: null,
    initialData: "",
    disabled: false,
  },
};
